workflows:
  android_build:
    name: Auto-create Android folder
    environment:
      flutter: stable
      xcode: none

    scripts:
      - name: Show directory
        script: ls -la

      - name: Create android folder
        script: flutter create .

      - name: Build debug apk
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
