workflows:
  android_build:
    name: Android Auto-Generate Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: none  # Disable iOS completely

    scripts:
      - name: Fix pubspec
        script: |
          flutter pub get

      - name: Generate missing android folder
        script: |
          if [ ! -d "android" ]; then
            echo "android/ folder missing — generating with flutter create ."
            flutter create .
          else
            echo "android folder already exists."
          fi

      - name: Build APK (Debug)
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
