workflows:
  android_only:
    name: Android-only auto-create
    max_build_duration: 60

    environment:
      flutter: stable
      
    scripts:
      - name: Print environment
        script: |
          echo "=== FLUTTER VERSION ==="
          flutter --version || true
          echo "=== PWD ==="
          pwd
          echo "=== ROOT FILES ==="
          ls -la

      - name: Force create platform files
        script: |
          set -ex
          # always run create to ensure android/ exists
          flutter create .

      - name: Show created files
        script: |
          echo "=== FILES AFTER CREATE ==="
          ls -la
          echo "=== ANDROID FOLDER LISTING ==="
          if [ -d android ]; then ls -la android || true; else echo "android missing"; fi

      - name: Get packages
        script: flutter pub get

      - name: Build debug apk
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
