workflows:
  android_build:
    name: Auto-create Android folder
    environment:
      flutter: stable
      xcode: none

    scripts:
      - name: Show repo root
        script: |
          echo "PWD: $(pwd)"
          echo "=== root files ==="
          ls -la

      - name: Create android folder (always)
        script: |
          set -x
          flutter create .

      - name: Show created android
        script: |
          echo "=== android listing ==="
          ls -la android || true

      - name: Build debug apk
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
